apiVersion: 1

datasources:
  - name: Olympic Training Postgres
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: olympic_training
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
